project:
  type: website
editor: source
website:
  favicon: /images/NEOF_favicon.png
  page-navigation: true
  title: NEOF BFX
  description: Useful bioinformatic resources as advised by NEOF
  navbar:
    title: NEOF BFX
    collapse-below: lg
    left:
    - text: Overview
      href: index.qmd
    - text: Linux
      href: Linux/index.qmd
    - text: Conda
      href: conda.qmd
    - text: AI
      href: ai.qmd
    - text: About us
      href: about_us.qmd
    right:
    - icon: house-fill
      href: https://neof.org.uk/training/
      aria-label: Neof website
    - icon: linkedin
      href: https://www.linkedin.com/in/training-neof/
      aria-label: LinkedIn
    - text: "![](/images/Bluesky_quarto_navbar.svg){height=20px}"
      href: https://bsky.app/profile/nerc-eof.bsky.social
  page-footer:
    left: |
      [![](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png){fig-alt="CC BY-SA 4.0" height=30px}](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    center: |
      [![](/images/NEOF_rounded_corners.png){fig-alt="NEOF" height=60px}](https://neof.org.uk/)
  sidebar:
  - id: Overview
    title: Overview
    style: floating
    align: left
    contents:
    - href: index.qmd
  - id: Linux
    title: Linux
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: Linux/index.qmd
    - section: Part 1
      contents:
      - href: Linux/01-Linux_Introduction.qmd
      - href: Linux/02-Starting.qmd
      - href: Linux/03-Directories_and_Files.qmd
      - href: Linux/04-Tips_and_tricks.qmd
      - href: Linux/05-Manipulating_directories.qmd
      - href: Linux/06-Exercise1.qmd
    - section: Part 2
      contents:
      - href: Linux/07-File_reading_and_processing.qmd
      - href: Linux/08-Recap.qmd
      - href: Linux/09-Fastq.qmd
      - href: Linux/10-Exercise2.qmd
    - section: Advanced topics
      contents:
      - href: Linux/11-Advanced_linux_practice.qmd
      - href: Linux/12-Advanced_practice_exercise.qmd
      - href: Linux/13-Bioinformatic_languages.qmd
    - section: Appendices
      contents:
      - href: Linux/a1-cheat_sheet.qmd
  - id: Conda
    title: Conda
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: conda.qmd
  - id: AI
    title: AI
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: ai.qmd
    - href: AI/LLMS.qmd
    - href: AI/Issues.qmd
    - href: AI/Using.qmd
  - id: About us
    title: About us
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: about_us.qmd
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 0.75em
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      light:
      - cosmo
      - css_files/styles.scss
      dark:
      - darkly
      - css_files/styles.scss
    embed-resources: false
    toc: true
    mainfont: Lexend