project:
  type: website
editor: source

#Website
website:
  page-navigation: true
  title: "PRIMEVAL DEITIES"
  description: "Primeval deity and other factions designed for the FIST RPG"
##Navbar
  navbar:
    logo: "images/kofi_button_blue.png"
    logo-href: https://ko-fi.com/waveofinspiration
    align: center
    title: false
    collapse-below: lg
###Navbar left
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Alternate history"
        href: history.qmd
      - text: "Nyxmera"
        href: nyxmera.qmd
      - text: "Tartarus"
        href: tartarus.qmd
      - text: "Proteus"
        href: proteus.qmd
      - text: "Gaia"
        href: gaia.qmd
      - text: "Missions"
        href: missions.qmd
      - text: "Items and traits"
        href: catalog.qmd
###Navbar right
    right:
      - icon: github
        href: https://github.com/m-gemmell/PRIMEVAL_DEITIES
        aria-label: GitHub

##Sidebar
  sidebar:
    - id: Alternate history
      title: "Alternate history"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: history.qmd

#Format
format:
  html:
    theme: 
    - styles.scss
    mainfont: Lexend
    toc: true