project:
  type: website
editor: source

#Website
website:
  favicon: /images/Gaia_favicon.png
  page-navigation: true
  title: "PRIMEVAL DEITIES"
  description: "Primeval deity and other factions designed for the FIST RPG"
##Navbar
  navbar:
    logo: "images/kofi_button_blue.png"
    logo-href: https://ko-fi.com/waveofinspiration
    align: center
    title: false
    collapse-below: lg
###Navbar left
    left:
      - text: "Overview"
        href: index.qmd
      - text: "History"
        href: history.qmd
      - text: "Nyxmera"
        href: nyxmera.qmd
      - text: "Tartarus"
        href: tartarus.qmd
      - text: "Proteus"
        href: proteus.qmd
      - text: "Gaia"
        href: gaia.qmd
      - text: "Missions"
        href: missions.qmd
      - text: "Catalog"
        href: catalog.qmd
###Navbar right
    right:
      - icon: github
        href: https://github.com/m-gemmell/PRIMEVAL_DEITIES
        aria-label: GitHub

##Sidebar
  sidebar:
    - id: Overview
      title: "Overview"
      style: "floating"
      align: left
      contents:
        - href: index.qmd
    - id: History
      title: "History"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: history.qmd
    - id: Nyxmera
      title: "Nyxmera"
      style: "floating"
      align: left
      contents:
        - href: nyxmera.qmd
        - href: Nyxmera/Followers.qmd
        - href: Nyxmera/Troops.qmd
        - href: Nyxmera/Starvatars.qmd
    - id: Tartarus
      title: "Tartarus"
      style: "floating"
      align: left
      contents:
        - href: tartarus.qmd
        - href: Tartarus/Followers.qmd
        - href: Tartarus/DOT_raiders.qmd
        - href: Tartarus/Kraken.qmd
        - href: Tartarus/Taloes.qmd
    - id: Proteus
      title: "Proteus"
      style: "floating"
      align: left
      contents:
        - href: proteus.qmd
        - href: Proteus/Triton_n_Delta.qmd
        - href: Proteus/Refraction_Sports.qmd
        - href: Proteus/Pumice_construction_ltd.qmd
        - href: Proteus/Water_bodies.qmd
    - id: Gaia
      title: "Gaia"
      style: "floating"
      align: left
      contents:
        - href: gaia.qmd
        - href: Gaia/TAG.qmd
    - id: Missions
      title: "Missions"
      style: "floating"
      align: left
      contents:
        - href: missions.qmd
        - href: Missions/M-POPS.qmd
    - id: Catalog
      title: "Catalog"
      style: "floating"
      align: left
      contents:
        - href: catalog.qmd


#Format
format:
  html:
    theme: 
    - styles.scss
    mainfont: Lexend
    toc: true